language: node_js

node_js:
  - "0.10"

addons:
  postgresql: "9.3"

services:
  - elasticsearch
  - redis-server

before_script:
  - psql -c 'create database template_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d template_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d template_postgis
  - psql -c 'CREATE EXTENSION "uuid-ossp";' -U postgres -d template_postgis
  - psql -d postgres -c "UPDATE pg_database SET datistemplate='true' WHERE datname='template_postgis';"
  - npm install -g pm2
  - export POSTGRESQL_HOST=localhost
  - export POSTGRESQL_PORT=5432
  - export POSTGRESQL_USER=postgres
  - export POSTGRESQL_PASSWORD=""
  - export ELASTICSEARCH_HOST=http://localhost:9200
  - export QUEUE_CLIENT="kue"
  - export PROJECTOR_PATH="$TRAVIS_BUILD_DIR"
  - export LEVEL_PATH="$PROJECTOR_PATH/tests/out/level"
  - export PROJECT_FILE_PATH="$PROJECTOR_PATH/tests/out/blueprint"
  - export STORES=postgresql,elasticsearch,level
  - export PORT=2000
